name: hzy_normal_tool
description: 项目开发基础工具
version: 0.0.2
homepage: "https://gitee.com/tengteng_fan/hzy_normal_tool.git"
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

    
